import 'package:flutter/material.dart';

class LanguageProvider extends ChangeNotifier {
  Locale _currentLocale = const Locale('en');

  Locale get currentLocale => _currentLocale;

  void changeLanguage(String code) {
    _currentLocale = Locale(code);
    notifyListeners();
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // General
      'title': 'Installer Portal',
      'login': 'Login',
      'email': 'Email',
      'password': 'Password',
      'logout': 'Logout',
      'cancel': 'Cancel',
      'submit': 'Submit',
      'required': 'Required',
      'store': 'Store',
      'date': 'Date',
      'technician': 'Technician',
      'photos_label': 'Photos',

      // Errors / Validation
      'invalid_credentials': 'Invalid Credentials',
      'invalid_email': 'Invalid email',
      'password_short': 'Password too short',
      'must_be_positive': 'Must be > 0',
      'account_disabled': 'Account Disabled',
      'user_created': 'User created successfully!',
      'error_no_job': 'Error: No job started.',
      'job_not_found_msg':
          'No open job found for this Store ID. Please contact Admin.',

      // Store Setup
      'store_setup': 'Store Verification',
      'enter_store': 'Enter Store ID to Verify',
      'store_id_label': 'Store ID',
      'store_id_helper': 'e.g., 12345-US',
      'verify': 'Verify Store',

      // Register / Checklist
      'register_setup': 'Register Setup',
      'start_checklist': 'Start Checklist',
      'submit_job': 'Submit Job',
      'incomplete': 'Incomplete',
      'job_complete': 'Job Complete',
      'job_complete_msg':
          'All required photos have been collected. Ready to submit?',
      'photo_taken': 'Photo taken',
      'pending': 'Pending',
      'uploading': 'Uploading...',
      'upload_success': 'Job submitted successfully!',
      'upload_fail': 'Submission failed. Please try again.',

      // Admin & User Mgmt
      'admin_dashboard': 'Admin Dashboard',
      'manage_users': 'Manage Users',
      'create_user': 'Create User',
      'add_user': 'Add User',
      'no_photos': 'No photos uploaded.',
      'no_users': 'No users found.',
      'active': 'Active',
      'disabled': 'Disabled',
      'create_new_user': 'Create New User',
      'new_account': 'New Account',
      'role': 'Role',
      'select_role': 'Select Role',
      'create_account': 'Create Account',
      'status_open': 'Status: OPEN (Waiting for Tech)',

      // Job Creation & Material Management (NEW)
      'create_new_job': 'Create New Job',
      'available_materials': 'Available Materials (Tap to Add)',
      'job_contents': 'Job Contents',
      'requires': 'Requires',
      'confirm_create_job': 'CONFIRM & CREATE JOB',
      'manage_materials': 'Manage Materials',
      'create_material_template': 'Create New Material Template',
      'material_name': 'Material Name',
      'photo_label': 'Required Photo Label',
      'save_template': 'Save Template',
      'material_saved': 'Material Saved',
      'enter_store_items': 'Enter Store ID and add items.',
      'job_created': 'Job Created Successfully',

      // ZIP Download (NEW)
      'zip_generating': 'Generating ZIP file... This may take a few seconds.',
      'zip_no_photos': 'No photos found to zip.',
      'zip_success': 'ZIP file downloaded successfully!',
      'zip_error': 'Error creating ZIP:',
      'zip_web_only': 'ZIP download is currently supported on Web only.',
    },
    'fr': {
      'title': 'Portail Installateur',
      'login': 'Connexion',
      'email': 'E-mail',
      'password': 'Mot de passe',
      'logout': 'Déconnexion',
      'cancel': 'Annuler',
      'submit': 'Soumettre',
      'required': 'Requis',
      'store': 'Magasin',
      'date': 'Date',
      'technician': 'Technicien',
      'photos_label': 'Photos',
      'invalid_credentials': 'Identifiants invalides',
      'invalid_email': 'E-mail invalide',
      'password_short': 'Mot de passe trop court',
      'must_be_positive': 'Doit être > 0',
      'account_disabled': 'Compte désactivé',
      'user_created': 'Utilisateur créé avec succès !',
      'error_no_job': 'Erreur : Aucune tâche commencée.',
      'job_not_found_msg':
          'Aucune tâche ouverte pour ce magasin. Contactez l\'admin.',
      'store_setup': 'Vérification Magasin',
      'enter_store': 'Entrez l\'ID du magasin',
      'store_id_label': 'ID Magasin',
      'store_id_helper': 'ex : 12345-FR',
      'verify': 'Vérifier',
      'register_setup': 'Config. Caisses',
      'start_checklist': 'Commencer',
      'submit_job': 'Soumettre',
      'incomplete': 'Incomplet',
      'job_complete': 'Travail Terminé',
      'job_complete_msg': 'Toutes les photos sont là. Soumettre ?',
      'photo_taken': 'Photo prise',
      'pending': 'En attente',
      'uploading': 'Envoi en cours...',
      'upload_success': 'Tâche soumise avec succès !',
      'upload_fail': 'Échec de la soumission. Réessayez.',
      'admin_dashboard': 'Tableau de Bord',
      'manage_users': 'Gérer Utilisateurs',
      'create_user': 'Créer Utilisateur',
      'add_user': 'Ajouter',
      'no_photos': 'Aucune photo.',
      'no_users': 'Aucun utilisateur trouvé.',
      'active': 'Actif',
      'disabled': 'Désactivé',
      'create_new_user': 'Nouvel Utilisateur',
      'new_account': 'Nouveau Compte',
      'role': 'Rôle',
      'select_role': 'Choisir un rôle',
      'create_account': 'Créer le Compte',
      'status_open': 'Statut : OUVERT (En attente du tech)',
      'create_new_job': 'Créer une Nouvelle Tâche',
      'available_materials': 'Matériaux Disponibles (Appuyer)',
      'job_contents': 'Contenu de la Tâche',
      'requires': 'Nécessite',
      'confirm_create_job': 'CONFIRMER & CRÉER',
      'manage_materials': 'Gérer les Matériaux',
      'create_material_template': 'Créer Modèle de Matériau',
      'material_name': 'Nom du Matériau',
      'photo_label': 'Étiquette Photo Requise',
      'save_template': 'Enregistrer le Modèle',
      'material_saved': 'Matériau Enregistré',
      'enter_store_items': 'Entrez ID Magasin et ajoutez des articles.',
      'job_created': 'Tâche Créée avec Succès',
      'zip_generating':
          'Génération du ZIP... Cela peut prendre quelques secondes.',
      'zip_no_photos': 'Aucune photo à zipper.',
      'zip_success': 'Fichier ZIP téléchargé avec succès !',
      'zip_error': 'Erreur de création ZIP :',
      'zip_web_only': 'Téléchargement ZIP supporté uniquement sur Web.',
    },
    'es': {
      'title': 'Portal Instalador',
      'login': 'Acceso',
      'email': 'Correo',
      'password': 'Contraseña',
      'logout': 'Salir',
      'cancel': 'Cancelar',
      'submit': 'Enviar',
      'required': 'Requerido',
      'store': 'Tienda',
      'date': 'Fecha',
      'technician': 'Técnico',
      'photos_label': 'Fotos',
      'invalid_credentials': 'Credenciales inválidas',
      'invalid_email': 'Correo inválido',
      'password_short': 'Contraseña muy corta',
      'must_be_positive': 'Debe ser > 0',
      'account_disabled': 'Cuenta Deshabilitada',
      'user_created': '¡Usuario creado con éxito!',
      'error_no_job': 'Error: No hay trabajo iniciado.',
      'job_not_found_msg':
          'No hay trabajo abierto para esta tienda. Contacte al admin.',
      'store_setup': 'Verificación Tienda',
      'enter_store': 'Ingrese ID de Tienda',
      'store_id_label': 'ID Tienda',
      'store_id_helper': 'ej: 12345-ES',
      'verify': 'Verificar',
      'register_setup': 'Config. Cajas',
      'start_checklist': 'Iniciar Lista',
      'submit_job': 'Enviar Trabajo',
      'incomplete': 'Incompleto',
      'job_complete': 'Trabajo Completo',
      'job_complete_msg': 'Fotos completas. ¿Enviar?',
      'photo_taken': 'Foto tomada',
      'pending': 'Pendiente',
      'uploading': 'Subiendo...',
      'upload_success': '¡Trabajo enviado con éxito!',
      'upload_fail': 'Falló el envío. Intente de nuevo.',
      'admin_dashboard': 'Panel Admin',
      'manage_users': 'Gestionar Usuarios',
      'create_user': 'Crear Usuario',
      'add_user': 'Añadir',
      'no_photos': 'Sin fotos.',
      'no_users': 'No se encontraron usuarios.',
      'active': 'Activo',
      'disabled': 'Deshabilitado',
      'create_new_user': 'Nuevo Usuario',
      'new_account': 'Nueva Cuenta',
      'role': 'Rol',
      'select_role': 'Seleccionar Rol',
      'create_account': 'Crear Cuenta',
      'status_open': 'Estado: ABIERTO (Esperando técnico)',
      'create_new_job': 'Crear Nuevo Trabajo',
      'available_materials': 'Materiales Disponibles (Tocar)',
      'job_contents': 'Contenido del Trabajo',
      'requires': 'Requiere',
      'confirm_create_job': 'CONFIRMAR Y CREAR',
      'manage_materials': 'Gestionar Materiales',
      'create_material_template': 'Crear Plantilla de Material',
      'material_name': 'Nombre del Material',
      'photo_label': 'Etiqueta de Foto Requerida',
      'save_template': 'Guardar Plantilla',
      'material_saved': 'Material Guardado',
      'enter_store_items': 'Ingrese ID Tienda y agregue artículos.',
      'job_created': 'Trabajo Creado con Éxito',
      'zip_generating': 'Generando ZIP... Esto puede tardar unos segundos.',
      'zip_no_photos': 'No se encontraron fotos para el zip.',
      'zip_success': '¡Archivo ZIP descargado con éxito!',
      'zip_error': 'Error al crear ZIP:',
      'zip_web_only': 'Descarga ZIP solo soportada en Web.',
    },
    'pt': {
      'title': 'Portal Instalador',
      'login': 'Entrar',
      'email': 'Email',
      'password': 'Palavra-Passe',
      'logout': 'Sair',
      'cancel': 'Cancelar',
      'submit': 'Enviar',
      'required': 'Obrigatório',
      'store': 'Loja',
      'date': 'Data',
      'technician': 'Técnico',
      'photos_label': 'Fotos',
      'invalid_credentials': 'Credenciais inválidas',
      'invalid_email': 'Email inválido',
      'password_short': 'Palavra-Passe muito curta',
      'must_be_positive': 'Deve ser > 0',
      'account_disabled': 'Conta Desativada',
      'user_created': 'Utilizador criado com sucesso!',
      'error_no_job': 'Erro: Nenhum trabalho iniciado.',
      'job_not_found_msg':
          'Nenhum trabalho aberto para esta loja. Contate o admin.',
      'store_setup': 'Verificação Loja',
      'enter_store': 'Digite ID da Loja',
      'store_id_label': 'ID Loja',
      'store_id_helper': 'ex: 12345-PT',
      'verify': 'Verificar',
      'register_setup': 'Config. Caixas',
      'start_checklist': 'Iniciar Lista',
      'submit_job': 'Enviar Trabalho',
      'incomplete': 'Incompleto',
      'job_complete': 'Trabalho Concluído',
      'job_complete_msg': 'Fotos completas. Enviar?',
      'photo_taken': 'Foto tirada',
      'pending': 'Pendente',
      'uploading': 'A carregar...',
      'upload_success': 'Trabalho enviado com sucesso!',
      'upload_fail': 'Falha no envio. Tente novamente.',
      'admin_dashboard': 'Painel Admin',
      'manage_users': 'Gerir Utilizadores',
      'create_user': 'Criar Utilizador',
      'add_user': 'Adicionar',
      'no_photos': 'Sem fotos.',
      'no_users': 'Nenhum utilizador encontrado.',
      'active': 'Ativo',
      'disabled': 'Desativado',
      'create_new_user': 'Novo Utilizador',
      'new_account': 'Nova Conta',
      'role': 'Função',
      'select_role': 'Selecione a Função',
      'create_account': 'Criar Conta',
      'status_open': 'Estado: ABERTO (Aguardando técnico)',
      'create_new_job': 'Criar Novo Trabalho',
      'available_materials': 'Materiais Disponíveis (Toque)',
      'job_contents': 'Conteúdo do Trabalho',
      'requires': 'Requer',
      'confirm_create_job': 'CONFIRMAR E CRIAR',
      'manage_materials': 'Gerir Materiais',
      'create_material_template': 'Criar Modelo de Material',
      'material_name': 'Nome do Material',
      'photo_label': 'Etiqueta da Foto Obrigatória',
      'save_template': 'Guardar Modelo',
      'material_saved': 'Material Guardado',
      'enter_store_items': 'Digite ID Loja e adicione itens.',
      'job_created': 'Trabalho Criado com Sucesso',
      'zip_generating': 'Gerando ZIP... Pode levar alguns segundos.',
      'zip_no_photos': 'Nenhuma foto encontrada para zipar.',
      'zip_success': 'Arquivo ZIP baixado com sucesso!',
      'zip_error': 'Erro ao criar ZIP:',
      'zip_web_only': 'Download ZIP suportado apenas na Web.',
    },
  };

  String translate(String key) {
    return _localizedValues[_currentLocale.languageCode]?[key] ?? key;
  }
}
